- name: Install devops tools with APT
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - terraform
    - vault
    - vagrant
    - inetutils-traceroute
    - inetutils-telnet
    - bind9-dnsutils
    - ipcalc
    - mtr-tiny
    - net-tools
