- name: Install HashiCorp GPG key
  ansible.builtin.import_tasks: install_hashicorp_key.yml
- name: Add HashiCorp APT repository
  ansible.builtin.import_tasks: add_hashicorp_ppa.yml
- name: Install Devops Tools
  ansible.builtin.import_tasks: install_tools.yml
- name: Install Helm
  ansible.builtin.import_tasks: install_helm.yml
- name: Install Terragrunt
  ansible.builtin.import_tasks: install_terragrunt.yml
- name: Install Yandex Cloud CLI
  ansible.builtin.import_tasks: install_yc.yml
