- name: Install common npm packages globally
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  loop:
    - yarn
    - pm2
    - nodemon
    - typescript
    - eslint
    - prettier
