- name: Install Claude Code extension
  ansible.builtin.import_tasks: install_claude_code.yml

- name: Install Gemini CLI
  ansible.builtin.import_tasks: install_gemini_cli.yml

- name: Install Codex CLI
  ansible.builtin.import_tasks: install_codex_cli.yml

- name: Install OpenCode AI
  ansible.builtin.import_tasks: install_opencode_ai.yml
