- name: Common | Kubernetes | Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: true
  become: true

- name: Common | Kubernetes | Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Common | Kubernetes | Download Kubernetes public key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: '0644'
  become: true

- name: Common | Kubernetes | Dearmor Kubernetes public key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true

- name: Common | Kubernetes | Remove temp key file
  ansible.builtin.file:
    path: /tmp/kubernetes-release.key
    state: absent
  become: true

- name: Common | Kubernetes | Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /"
    filename: kubernetes
    state: present
  become: true

- name: Common | Kubernetes | Install Kubernetes tools
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true
  become: true

- name: Common | Kubernetes | Hold Kubernetes tools
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true
