- name: Install common development tools
  ansible.builtin.import_tasks: install_devtools.yml

- name: Install Task runner
  ansible.builtin.import_tasks: install_task.yml

- name: Install GitHub CLI
  ansible.builtin.import_tasks: install_github_cli.yml

- name: Install Docker
  ansible.builtin.import_tasks: install_docker.yml
