---
- name: Setup WSL environment
  hosts: localhost
  connection: local
  become: yes

  roles:
    - common
    - golang
    - devops
    - nodejs
    - ai
    - role: ubuntu-desktop
      when: env is defined and env == "ubuntu-desktop"
