---
- name: Setup Ubuntu Server environment
  hosts: localhost
  connection: local
  become: true

  roles:
    - ubuntu_server
    - ubuntu_common
    - common
    - golang
    - devops
    - nodejs
    - ai
