- name: Ubuntu Common | Ensure snapd is installed
  ansible.builtin.apt:
    name: snapd
    state: present
  when: ansible_os_family == 'Debian'

- name: Install smartmontools
  ansible.builtin.import_tasks: install_smartmontools.yml
